// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ri_p98D8J3Xm7gBlrWVHcRvsIm5Z2bw',
    appId: '1:1062180731311:web:9810ca05707d1d7299175a',
    messagingSenderId: '1062180731311',
    projectId: 'jose-portfolio-flutterweb-2',
    authDomain: 'jose-portfolio-flutterweb-2.firebaseapp.com',
    storageBucket: 'jose-portfolio-flutterweb-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxmqy4QcyPCtEPHmKBxJYxsh9Gp-DwcMw',
    appId: '1:1062180731311:android:436c059175b9602599175a',
    messagingSenderId: '1062180731311',
    projectId: 'jose-portfolio-flutterweb-2',
    storageBucket: 'jose-portfolio-flutterweb-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCw8seqVkux_W_Q817IUdVbAibXpZjpDk',
    appId: '1:1062180731311:ios:8e506fe3a63babfe99175a',
    messagingSenderId: '1062180731311',
    projectId: 'jose-portfolio-flutterweb-2',
    storageBucket: 'jose-portfolio-flutterweb-2.appspot.com',
    iosClientId: '1062180731311-ra3s4frvi9t9p1b9gpgk0a2n5cm0b09d.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCw8seqVkux_W_Q817IUdVbAibXpZjpDk',
    appId: '1:1062180731311:ios:8e506fe3a63babfe99175a',
    messagingSenderId: '1062180731311',
    projectId: 'jose-portfolio-flutterweb-2',
    storageBucket: 'jose-portfolio-flutterweb-2.appspot.com',
    iosClientId: '1062180731311-ra3s4frvi9t9p1b9gpgk0a2n5cm0b09d.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalPortfolio',
  );
}
